/**
 * Jellyfin API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 10.7.7
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export type Architecture = 'X86' | 'X64' | 'Arm' | 'Arm64' | 'Wasm';

export const Architecture = {
    X86: 'X86' as Architecture,
    X64: 'X64' as Architecture,
    Arm: 'Arm' as Architecture,
    Arm64: 'Arm64' as Architecture,
    Wasm: 'Wasm' as Architecture
};

