/**
 * Jellyfin API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 10.7.7
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Create new playlist dto.
 */
export interface CreatePlaylistDto { 
    /**
     * Gets or sets the name of the new playlist.
     */
    Name?: string | null;
    /**
     * Gets or sets item ids to add to the playlist.
     */
    Ids?: Array<string> | null;
    /**
     * Gets or sets the user id.
     */
    UserId?: string | null;
    /**
     * Gets or sets the media type.
     */
    MediaType?: string | null;
}

