/**
 * Jellyfin API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 10.7.7
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaderInfo } from './httpHeaderInfo';


export interface DeviceIdentification { 
    /**
     * Gets or sets the name of the friendly.
     */
    FriendlyName?: string | null;
    /**
     * Gets or sets the model number.
     */
    ModelNumber?: string | null;
    /**
     * Gets or sets the serial number.
     */
    SerialNumber?: string | null;
    /**
     * Gets or sets the name of the model.
     */
    ModelName?: string | null;
    /**
     * Gets or sets the model description.
     */
    ModelDescription?: string | null;
    /**
     * Gets or sets the model URL.
     */
    ModelUrl?: string | null;
    /**
     * Gets or sets the manufacturer.
     */
    Manufacturer?: string | null;
    /**
     * Gets or sets the manufacturer URL.
     */
    ManufacturerUrl?: string | null;
    /**
     * Gets or sets the headers.
     */
    Headers?: Array<HttpHeaderInfo> | null;
}

