/**
 * Jellyfin API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 10.7.7
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ScrollDirection } from './scrollDirection';
import { SortOrder } from './sortOrder';


/**
 * Defines the display preferences for any item that supports them (usually Folders).
 */
export interface DisplayPreferencesDto { 
    /**
     * Gets or sets the user id.
     */
    Id?: string | null;
    /**
     * Gets or sets the type of the view.
     */
    ViewType?: string | null;
    /**
     * Gets or sets the sort by.
     */
    SortBy?: string | null;
    /**
     * Gets or sets the index by.
     */
    IndexBy?: string | null;
    /**
     * Gets or sets a value indicating whether [remember indexing].
     */
    RememberIndexing?: boolean;
    /**
     * Gets or sets the height of the primary image.
     */
    PrimaryImageHeight?: number;
    /**
     * Gets or sets the width of the primary image.
     */
    PrimaryImageWidth?: number;
    /**
     * Gets or sets the custom prefs.
     */
    CustomPrefs?: { [key: string]: string; } | null;
    /**
     * Gets or sets the scroll direction.
     */
    ScrollDirection?: ScrollDirection;
    /**
     * Gets or sets a value indicating whether to show backdrops on this item.
     */
    ShowBackdrop?: boolean;
    /**
     * Gets or sets a value indicating whether [remember sorting].
     */
    RememberSorting?: boolean;
    /**
     * Gets or sets the sort order.
     */
    SortOrder?: SortOrder;
    /**
     * Gets or sets a value indicating whether [show sidebar].
     */
    ShowSidebar?: boolean;
    /**
     * Gets or sets the client.
     */
    Client?: string | null;
}

