/**
 * Jellyfin API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 10.7.7
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ForgotPasswordAction } from './forgotPasswordAction';


export interface ForgotPasswordResult { 
    /**
     * Gets or sets the action.
     */
    Action?: ForgotPasswordAction;
    /**
     * Gets or sets the pin file.
     */
    PinFile?: string | null;
    /**
     * Gets or sets the pin expiration date.
     */
    PinExpirationDate?: string | null;
}

