/**
 * Jellyfin API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 10.7.7
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { LibraryTypeOptionsDto } from './libraryTypeOptionsDto';
import { LibraryOptionInfoDto } from './libraryOptionInfoDto';


/**
 * Library options result dto.
 */
export interface LibraryOptionsResultDto { 
    /**
     * Gets or sets the metadata savers.
     */
    MetadataSavers?: Array<LibraryOptionInfoDto> | null;
    /**
     * Gets or sets the metadata readers.
     */
    MetadataReaders?: Array<LibraryOptionInfoDto> | null;
    /**
     * Gets or sets the subtitle fetchers.
     */
    SubtitleFetchers?: Array<LibraryOptionInfoDto> | null;
    /**
     * Gets or sets the type options.
     */
    TypeOptions?: Array<LibraryTypeOptionsDto> | null;
}

