/**
 * Jellyfin API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 10.7.7
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { NameValuePair } from './nameValuePair';


export interface ListingsProviderInfo { 
    Id?: string | null;
    Type?: string | null;
    Username?: string | null;
    Password?: string | null;
    ListingsId?: string | null;
    ZipCode?: string | null;
    Country?: string | null;
    Path?: string | null;
    EnabledTuners?: Array<string> | null;
    EnableAllTuners?: boolean;
    NewsCategories?: Array<string> | null;
    SportsCategories?: Array<string> | null;
    KidsCategories?: Array<string> | null;
    MovieCategories?: Array<string> | null;
    ChannelMappings?: Array<NameValuePair> | null;
    MoviePrefix?: string | null;
    PreferredLanguage?: string | null;
    UserAgent?: string | null;
}

