/**
 * Jellyfin API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 10.7.7
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { NameValuePair } from './nameValuePair';
import { ExternalIdInfo } from './externalIdInfo';
import { CountryInfo } from './countryInfo';
import { ParentalRating } from './parentalRating';
import { CultureDto } from './cultureDto';


export interface MetadataEditorInfo { 
    ParentalRatingOptions?: Array<ParentalRating> | null;
    Countries?: Array<CountryInfo> | null;
    Cultures?: Array<CultureDto> | null;
    ExternalIdInfos?: Array<ExternalIdInfo> | null;
    ContentType?: string | null;
    ContentTypeOptions?: Array<NameValuePair> | null;
}

