/**
 * Jellyfin API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 10.7.7
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Enum PlaystateCommand.
 */
export type PlaystateCommand = 'Stop' | 'Pause' | 'Unpause' | 'NextTrack' | 'PreviousTrack' | 'Seek' | 'Rewind' | 'FastForward' | 'PlayPause';

export const PlaystateCommand = {
    Stop: 'Stop' as PlaystateCommand,
    Pause: 'Pause' as PlaystateCommand,
    Unpause: 'Unpause' as PlaystateCommand,
    NextTrack: 'NextTrack' as PlaystateCommand,
    PreviousTrack: 'PreviousTrack' as PlaystateCommand,
    Seek: 'Seek' as PlaystateCommand,
    Rewind: 'Rewind' as PlaystateCommand,
    FastForward: 'FastForward' as PlaystateCommand,
    PlayPause: 'PlayPause' as PlaystateCommand
};

