/**
 * Jellyfin API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 10.7.7
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { BaseItemDto } from './baseItemDto';
import { QueueItem } from './queueItem';


/**
 * Class PlaybackStopInfo.
 */
export interface PlaybackStopInfo { 
    /**
     * Gets or sets the item.
     */
    Item?: BaseItemDto | null;
    /**
     * Gets or sets the item identifier.
     */
    ItemId?: string;
    /**
     * Gets or sets the session id.
     */
    SessionId?: string | null;
    /**
     * Gets or sets the media version identifier.
     */
    MediaSourceId?: string | null;
    /**
     * Gets or sets the position ticks.
     */
    PositionTicks?: number | null;
    /**
     * Gets or sets the live stream identifier.
     */
    LiveStreamId?: string | null;
    /**
     * Gets or sets the play session identifier.
     */
    PlaySessionId?: string | null;
    /**
     * Gets or sets a value indicating whether this MediaBrowser.Model.Session.PlaybackStopInfo is failed.
     */
    Failed?: boolean;
    NextMediaType?: string | null;
    PlaylistItemId?: string | null;
    NowPlayingQueue?: Array<QueueItem> | null;
}

