/**
 * Jellyfin API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 10.7.7
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export type ProgramAudio = 'Mono' | 'Stereo' | 'Dolby' | 'DolbyDigital' | 'Thx' | 'Atmos';

export const ProgramAudio = {
    Mono: 'Mono' as ProgramAudio,
    Stereo: 'Stereo' as ProgramAudio,
    Dolby: 'Dolby' as ProgramAudio,
    DolbyDigital: 'DolbyDigital' as ProgramAudio,
    Thx: 'Thx' as ProgramAudio,
    Atmos: 'Atmos' as ProgramAudio
};

