/**
 * Jellyfin API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 10.7.7
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { RemoteImageInfo } from './remoteImageInfo';


/**
 * Class RemoteImageResult.
 */
export interface RemoteImageResult { 
    /**
     * Gets or sets the images.
     */
    Images?: Array<RemoteImageInfo> | null;
    /**
     * Gets or sets the total record count.
     */
    TotalRecordCount?: number;
    /**
     * Gets or sets the providers.
     */
    Providers?: Array<string> | null;
}

