/**
 * Jellyfin API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 10.7.7
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export type RepeatMode = 'RepeatNone' | 'RepeatAll' | 'RepeatOne';

export const RepeatMode = {
    RepeatNone: 'RepeatNone' as RepeatMode,
    RepeatAll: 'RepeatAll' as RepeatMode,
    RepeatOne: 'RepeatOne' as RepeatMode
};

