/**
 * Jellyfin API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 10.7.7
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ProfileCondition } from './profileCondition';
import { DlnaProfileType } from './dlnaProfileType';


export interface ResponseProfile { 
    Container?: string | null;
    AudioCodec?: string | null;
    VideoCodec?: string | null;
    Type?: DlnaProfileType;
    OrgPn?: string | null;
    MimeType?: string | null;
    Conditions?: Array<ProfileCondition> | null;
}

