/**
 * Jellyfin API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 10.7.7
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export type TranscodeReason = 'ContainerNotSupported' | 'VideoCodecNotSupported' | 'AudioCodecNotSupported' | 'ContainerBitrateExceedsLimit' | 'AudioBitrateNotSupported' | 'AudioChannelsNotSupported' | 'VideoResolutionNotSupported' | 'UnknownVideoStreamInfo' | 'UnknownAudioStreamInfo' | 'AudioProfileNotSupported' | 'AudioSampleRateNotSupported' | 'AnamorphicVideoNotSupported' | 'InterlacedVideoNotSupported' | 'SecondaryAudioNotSupported' | 'RefFramesNotSupported' | 'VideoBitDepthNotSupported' | 'VideoBitrateNotSupported' | 'VideoFramerateNotSupported' | 'VideoLevelNotSupported' | 'VideoProfileNotSupported' | 'AudioBitDepthNotSupported' | 'SubtitleCodecNotSupported' | 'DirectPlayError';

export const TranscodeReason = {
    ContainerNotSupported: 'ContainerNotSupported' as TranscodeReason,
    VideoCodecNotSupported: 'VideoCodecNotSupported' as TranscodeReason,
    AudioCodecNotSupported: 'AudioCodecNotSupported' as TranscodeReason,
    ContainerBitrateExceedsLimit: 'ContainerBitrateExceedsLimit' as TranscodeReason,
    AudioBitrateNotSupported: 'AudioBitrateNotSupported' as TranscodeReason,
    AudioChannelsNotSupported: 'AudioChannelsNotSupported' as TranscodeReason,
    VideoResolutionNotSupported: 'VideoResolutionNotSupported' as TranscodeReason,
    UnknownVideoStreamInfo: 'UnknownVideoStreamInfo' as TranscodeReason,
    UnknownAudioStreamInfo: 'UnknownAudioStreamInfo' as TranscodeReason,
    AudioProfileNotSupported: 'AudioProfileNotSupported' as TranscodeReason,
    AudioSampleRateNotSupported: 'AudioSampleRateNotSupported' as TranscodeReason,
    AnamorphicVideoNotSupported: 'AnamorphicVideoNotSupported' as TranscodeReason,
    InterlacedVideoNotSupported: 'InterlacedVideoNotSupported' as TranscodeReason,
    SecondaryAudioNotSupported: 'SecondaryAudioNotSupported' as TranscodeReason,
    RefFramesNotSupported: 'RefFramesNotSupported' as TranscodeReason,
    VideoBitDepthNotSupported: 'VideoBitDepthNotSupported' as TranscodeReason,
    VideoBitrateNotSupported: 'VideoBitrateNotSupported' as TranscodeReason,
    VideoFramerateNotSupported: 'VideoFramerateNotSupported' as TranscodeReason,
    VideoLevelNotSupported: 'VideoLevelNotSupported' as TranscodeReason,
    VideoProfileNotSupported: 'VideoProfileNotSupported' as TranscodeReason,
    AudioBitDepthNotSupported: 'AudioBitDepthNotSupported' as TranscodeReason,
    SubtitleCodecNotSupported: 'SubtitleCodecNotSupported' as TranscodeReason,
    DirectPlayError: 'DirectPlayError' as TranscodeReason
};

