/**
 * Jellyfin API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 10.7.7
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface TunerHostInfo { 
    Id?: string | null;
    Url?: string | null;
    Type?: string | null;
    DeviceId?: string | null;
    FriendlyName?: string | null;
    ImportFavoritesOnly?: boolean;
    AllowHWTranscoding?: boolean;
    EnableStreamLooping?: boolean;
    Source?: string | null;
    TunerCount?: number;
    UserAgent?: string | null;
}

